services:
  dart-server:
    build: .
    container_name: dart-bot
    restart: always
    depends_on:
      - postgres
    environment:
      - API_TELEGRAM_KEY=${API_TELEGRAM_KEY}
      - DATABASE_URL=postgres://postgres:password@postgres:5432/bot_db?sslmode=disable
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: bot-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  internal:
    driver: bridge