services:
  dart-server:
    build: .
    container_name: dart-bot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - API_TELEGRAM_KEY=${API_TELEGRAM_KEY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: bot-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - internal

volumes:
  postgres-data:

networks:
  internal:
    driver: bridge